server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: liu
    password: Liu1988226
    url: jdbc:mysql://cdb-kx7bfwy2.bj.tencentcdb.com:10187/springJpa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

  profiles:
    active: classpath:logback-black.xml
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mybatis/*.xml


